name: 🚀 Deploy to Strato via SFTP

on:
  push:
    branches:
      - main  # or master, if that’s your default

jobs:
  sftp-deploy:
    name: Upload website to Strato via SFTP
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 🚀 Deploy via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          source: "workflow/dist/"                     # Change if you use dist/build
          target: "/"
          strip_components: 0       # Remove root folder from archive
